export enum ENDPOINTS {
  LOGIN = "login",
  PASSWORD_RESET = "password-reset",
  NEW_PASSWORD = "new-password",
  NEW_PASSWORD_CHECK = "new-password-check",
  REGISTRATION = "registration",
  VERIFY = "verify",
  LOGOUT = "logout",
  NEW_COURSE = "new-course",
  USERS_LIST = "users-list",
  COURSES = "courses",
  COURSE = "course",
  AVAILABLE_COURSES = "available-courses",
  REGISTER_COURSE = "register-course",
  MY_COURSES_STUDENT = "my-courses-student",
  MY_COURSES_TEACHER = "my-courses-teacher",
  TAGS = "tags",
  SAVE_TAG = "save-tag",
  TAGS_LIST = "tags-list",
  DELETE_TAG = "delete-tag",
  EXERCISE = "exercise",
  EXERCISES_TEACHER = "exercises/teacher",
  EXERCISES_STUDENT = "exercises/student",
  EXERCISE_LIST = "exercise-list",
  SAVE_EXERCISE = "save-exercise",
  DELETE_EXERCISE = "delete-exercise",
}
